runtime: nodejs20
service: dev
env_variables:
  NODE_ENV: development
  PROJECT_NAME: "WebAuthn Demo"
  GOOGLE_CLOUD_PROJECT: try-webauthn
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
